export const collaborators = [
  {
    name: "Tiago Lacerda Ferreira",
    position: "Front",
    team: "Suporte",
    shift: "14:00 - 22:00",
    dayOff: "Terça",
    email: "tiago.ferreira@example.com",
    password: "Tiago123!",
  },
  {
    name: "Luiz Felipe Azevedo de Brito",
    position: "Back",
    team: "Suporte",
    shift: "14:00 - 22:00",
    dayOff: "Quinta",
    email: "luiz.brito@example.com",
    password: "Luiz123!",
  },
  {
    name: "Heitor",
    position: "Jogos",
    team: "Suporte",
    shift: "22:00 - 06:00",
    dayOff: "Quarta",
    email: "heitor@example.com",
    password: "Heitor123!",
  },
  {
    name: "Kevyn",
    position: "Back",
    team: "Suporte",
    shift: "22:00 - 06:00",
    dayOff: "Segunda",
    email: "kevyn@example.com",
    password: "Kevyn123!",
  },
  {
    name: "David",
    position: "Front",
    team: "Suporte",
    shift: "06:00 - 14:00",
    dayOff: "Segunda",
    email: "david@example.com",
    password: "David123!",
  },
  {
    name: "Lavique",
    position: "Back",
    team: "Suporte",
    shift: "06:00 - 14:00",
    dayOff: "Sexta",
    email: "lavique@example.com",
    password: "Lavique123!",
  },
  {
    name: "Well",
    position: "Supervisor I",
    team: "Segurança",
    shift: "14:00 - 22:00",
    dayOff: "Sexta",
    email: "well@example.com",
    password: "Well123!",
  },
  {
    name: "Well 2",
    position: "Supervisor I",
    team: "Segurança",
    shift: "14:00 - 22:00",
    dayOff: "Sexta",
    email: "well2@example.com",
    password: "Well2123!",
  },
  {
    name: "Well 3",
    position: "Supervisor I",
    team: "Segurança",
    shift: "14:00 - 22:00",
    dayOff: "Sexta",
    email: "well3@example.com",
    password: "Well3123!",
  },
  {
    name: "Well 4",
    position: "Supervisor I",
    team: "Segurança",
    shift: "14:00 - 22:00",
    dayOff: "Sexta",
    email: "well4@example.com",
    password: "Well4123!",
  },
  {
    name: "Well 5",
    position: "Supervisor I",
    team: "Segurança",
    shift: "14:00 - 22:00",
    dayOff: "Sexta",
    email: "well5@example.com",
    password: "Well5123!",
  },
  {
    name: "Well 6",
    position: "Supervisor I",
    team: "Segurança",
    shift: "14:00 - 22:00",
    dayOff: "Sexta",
    email: "well6@example.com",
    password: "Well6123!",
  },
  {
    name: "Well 7",
    position: "Supervisor I",
    team: "Segurança",
    shift: "14:00 - 22:00",
    dayOff: "Sexta",
    email: "well7@example.com",
    password: "Well7123!",
  },
  {
    name: "Demi",
    position: "Supervisor I",
    team: "Atendimento",
    shift: "14:00 - 22:00",
    dayOff: "Sexta",
    email: "demi@example.com",
    password: "Demi123!",
  },
  {
    name: "Demi 2",
    position: "Supervisor I",
    team: "Atendimento",
    shift: "14:00 - 22:00",
    dayOff: "Sexta",
    email: "demi2@example.com",
    password: "Demi2123!",
  },
  {
    name: "Demi 3",
    position: "Supervisor I",
    team: "Atendimento",
    shift: "14:00 - 22:00",
    dayOff: "Sexta",
    email: "demi3@example.com",
    password: "Demi3123!",
  },
  {
    name: "Demi 4",
    position: "Supervisor I",
    team: "Atendimento",
    shift: "14:00 - 22:00",
    dayOff: "Sexta",
    email: "demi4@example.com",
    password: "Demi4123!",
  },
  {
    name: "Demi 5",
    position: "Supervisor I",
    team: "Atendimento",
    shift: "14:00 - 22:00",
    dayOff: "Sexta",
    email: "demi5@example.com",
    password: "Demi5123!",
  },
  {
    name: "Demi 6",
    position: "Supervisor I",
    team: "Atendimento",
    shift: "14:00 - 22:00",
    dayOff: "Sexta",
    email: "demi6@example.com",
    password: "Demi6123!",
  },
  {
    name: "Demi 7",
    position: "Supervisor I",
    team: "Atendimento",
    shift: "14:00 - 22:00",
    dayOff: "Sexta",
    email: "demi7@example.com",
    password: "Demi7123!",
  },
];
